name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install oc4
        run: |
          curl "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz" > oc.tar.gz
          tar xvzf oc.tar.gz
          rm oc.tar.gz
          sudo mv oc /usr/local/bin
          echo "oc CLI $(oc version)"
