name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test python vtk
        run: |
          sudo apt-get update && sudo apt-get install python3-pip python3-pytest python3-pandas python3-scipy python3-h5py python3-vtk7
          python -c 'import vtk'
