name: CI

on: [push]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: test python
        run: |
          python -c "import sys; print(sys.stdout.encoding); print('汉字')"
