name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test script
        run: |
          echo "tell application \"Finder\" to close windows" > script.b && osascript script.b
