name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test script
        run: |
            set -e
            echo "tell application \"System Events\"
            click at {123,456}
            end tell
            " > b.scpt
            osascript b.scpt
