name: CI

on: [push]

jobs:
  job1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test yarn
        run: |
          git clone https://github.com/vercel/vercel
          cd vercel
          yarn install
  job2:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test yarn
        run: |
          git clone https://github.com/vercel/vercel
          cd vercel
          yarn install
  job3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test yarn
        run: |
          git clone https://github.com/vercel/vercel
          cd vercel
          yarn install
  job4:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test yarn
        run: |
          git clone https://github.com/vercel/vercel
          cd vercel
          yarn install
